NP <- read.csv(file = "~/CLionProjects/untitled/NP.csv", check.names = FALSE)
L <- read.csv(file = "~/CLionProjects/untitled/L.csv", check.names = FALSE)
GP <- read.csv(file = "~/CLionProjects/untitled/GP.csv", check.names = FALSE)
VP35 <- read.csv(file = "~/CLionProjects/untitled/VP35.csv", check.names = FALSE)
VP30 <- read.csv(file = "~/CLionProjects/untitled/VP30.csv", check.names = FALSE)
VP40 <- read.csv(file = "~/CLionProjects/untitled/VP40.csv", check.names = FALSE)
VP24 <- read.csv(file = "~/CLionProjects/untitled/VP24.csv", check.names = FALSE)
Global <- read.csv(file = "~/CLionProjects/untitled/global.csv", check.names = FALSE)
CSV_3 <- read.csv(file = "~/CLionProjects/untitled/3_2.csv", check.names = FALSE)
library(phangorn)
##L
Ltree = upgma(L)
neiL = nj(as.dist(L))
png(filename="~/CLionProjects/untitled/UPGMA_geneL.png")
plot(Ltree)
dev.off()
png(filename="~/CLionProjects/untitled/NJ_geneL.png")
plot(neiL)
dev.off()

##GP
GPtree = upgma(GP)
neiGP = nj(as.dist(GP))
png(filename="~/CLionProjects/untitled/UPGMA_geneGP.png")
plot(GPtree)
dev.off()
png(filename="~/CLionProjects/untitled/NJ_geneGP.png")
plot(neiGP)
dev.off()

##VP35
VP35tree = upgma(VP35)
nei35 = nj(as.dist(VP35))
png(filename="~/CLionProjects/untitled/UPGMA_geneVP35.png")
plot(VP35tree)
dev.off()
png(filename="~/CLionProjects/untitled/NJ_geneVP35.png")
plot(nei35)
dev.off()

##VP30
VP30tree = upgma(VP30)
png(filename="~/CLionProjects/untitled/UPGMA_geneVP30.png")
plot(VP30tree)
dev.off()
neiVP30tree = nj(as.dist(VP30))
png(filename="~/CLionProjects/untitled/NJ_geneVP30.png")
plot(neiVP30tree)
dev.off()


##VP40
VP40tree = upgma(VP40)
png(filename="~/CLionProjects/untitled/UPGMA_geneVP40.png")
plot(VP40tree)
dev.off()
neiVP40tree = nj(as.dist(VP40))
png(filename="~/CLionProjects/untitled/NJ_geneVP40.png")
plot(neiVP40tree)
dev.off()

##VP24
VP24tree = upgma(VP24)
png(filename="~/CLionProjects/untitled/UPGMA_geneVP24.png")
plot(VP24tree)
dev.off()
neiVP24tree = nj(as.dist(VP24))
png(filename="~/CLionProjects/untitled/NJ_geneVP24.png")
plot(neiVP24tree)
dev.off()

##NP
NPtree = upgma(NP)
png(filename="~/CLionProjects/untitled/UPGMA_geneNP.png")
plot(NPtree)
dev.off()
neiNPtree = nj(as.dist(NP))
png(filename="~/CLionProjects/untitled/NJ_geneNP.png")
plot(neiNPtree)
dev.off()

##global
globaltree = upgma(Global)
png(filename="~/CLionProjects/untitled/UPGMA_global.png")
plot(globaltree)
dev.off()
neiglobal = nj(as.dist(Global))
png(filename="~/CLionProjects/untitled/NJ_global.png")
plot(neiglobal)
dev.off()
library(phangorn)
##3-2
tree3 = upgma(CSV_3)
png(filename="~/CLionProjects/untitled/UPGMA_3-2.png")
plot(tree3)
dev.off()
nei_3 = nj(as.dist(CSV_3))
png(filename="~/CLionProjects/untitled/NJ_3-2.png")
plot(nei_3)
dev.off()
mergedTree <- consensus(Ltree, GPtree, NPtree, VP30tree, VP35tree, VP40tree, VP24tree, p = 1, check.labels = TRUE)
plot(mergedTree)